### ISSUE TITLE
Question ?! Gestion des resto' 

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/api-formenu#42]
Est ce qu'on devrait pas potentiellement rajouter "company" sur tous les éléments de l'api ? pour pouvoir filtrer facilement dessus ? & avoir une séparation plus simple à gérer ?

**Comment by LightInn** [comment]
Moi ça me parais pas déconnant, car de toute facon tout est intiment lier a l'idEntreprise et ca permet de faire un Index dans les tables pour la vitesse

**Comment by WadeFade** [comment]
J'en ai discuté avec Andy en vocal, et je suis d'accord

**Comment by CinquinAndy** [comment]
Après vous tous beau
